apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding
spec:
  selector:
    matchLabels:
      app: embedding
  template:
    metadata:
      labels:
        app: embedding
    spec:
      containers:
        - name: embedding
          image: ornite/octusai-embedding:latest
          resources:
            limits:
              cpu: "1"
              memory: "8Gi"
              nvidia.com/gpu: 1
          ports:
            - containerPort: 50052
