# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x05proto\"1\n\x0cImageRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"0\n\x0bTextRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"r\n\x11\x45mbeddingResponse\x12\x19\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0b.proto.Data\x12\r\n\x05model\x18\x02 \x01(\t\x12\x16\n\x0e\x65xecution_time\x18\x03 \x01(\x02\x12\x1b\n\x05usage\x18\x04 \x01(\x0b\x32\x0c.proto.Usage\")\n\x04\x44\x61ta\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x0e\n\x06length\x18\x02 \x01(\x02\"\x1d\n\x05Usage\x12\x14\n\x0ctotal_tokens\x18\x01 \x01(\x02\x32\x98\x01\n\x10\x45mbeddingService\x12\x42\n\x11GetImageEmbedding\x12\x13.proto.ImageRequest\x1a\x18.proto.EmbeddingResponse\x12@\n\x10GetTextEmbedding\x12\x12.proto.TextRequest\x1a\x18.proto.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=75
  _globals['_TEXTREQUEST']._serialized_start=77
  _globals['_TEXTREQUEST']._serialized_end=125
  _globals['_EMBEDDINGRESPONSE']._serialized_start=127
  _globals['_EMBEDDINGRESPONSE']._serialized_end=241
  _globals['_DATA']._serialized_start=243
  _globals['_DATA']._serialized_end=284
  _globals['_USAGE']._serialized_start=286
  _globals['_USAGE']._serialized_end=315
  _globals['_EMBEDDINGSERVICE']._serialized_start=318
  _globals['_EMBEDDINGSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
